# Generated by Django 5.1.2 on 2024-11-03 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_blog_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='published_at',
        ),
    ]
