# Generated by Django 5.1.2 on 2024-11-03 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_main_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
