# Generated by Django 5.1.2 on 2024-11-04 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('TE', 'Technology'), ('LI', 'Lifestyle'), ('TR', 'Travel'), ('FO', 'Food')], default='TE', max_length=2)),
            ],
        ),
    ]
