# Generated by Django 5.1.2 on 2024-11-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Technology'), ('Life', 'Lifestyle'), ('Edu', 'Education'), ('Ent', 'Entertainment')], default='Tech', max_length=20),
        ),
    ]
