# Generated by Django 5.1.2 on 2024-11-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_photo',
            field=models.ImageField(default='blog_photos/code.jpg', upload_to='blog_photos/'),
        ),
    ]
