# Generated by Django 4.2.16 on 2024-11-05 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_image_alter_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('HEALTH', 'Health'), ('LIFESTYLE', 'Lifestyle'), ('SPORTS', 'Sports'), ('EDUCATION', 'Education')], default='TECH', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 3, 8, 39, 281418)),
        ),
    ]
