# Generated by Django 5.0.6 on 2024-11-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_kind_alter_blog_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='kind',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('sport', 'Sport')], default='business', max_length=64),
        ),
    ]
