# Generated by Django 5.1.2 on 2024-11-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('games', 'Games'), ('advice', 'Advice'), ('business', 'Business')], default='genral', max_length=50),
        ),
    ]
