# Generated by Django 5.1.2 on 2024-11-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('games', 'Games'), ('advice', 'Advice'), ('business', 'Business')], max_length=50),
        ),
    ]
