# Generated by Django 5.1.2 on 2024-11-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
