# Generated by Django 5.1.2 on 2024-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Travel', 'Travel'), ('Sport', 'Sport'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Business', 'Business'), ('Culture', 'Culture')], default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
