# Generated by Django 5.1.2 on 2024-11-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
