# Generated by Django 5.1.2 on 2024-11-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_publishedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Genr', 'General'), ('Trav', 'Travel'), ('Sprt', 'Sport'), ('Entr', 'Entertainment'), ('Tech', 'Technology'), ('Busi', 'Business'), ('Cult', 'Culture')], max_length=256),
        ),
    ]
