# Generated by Django 5.1.2 on 2024-11-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="poster",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
    ]
