# Generated by Django 5.1.2 on 2024-11-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("tech", "Technology"),
                    ("life", "Lifestyle"),
                    ("edu", "Education"),
                    ("news", "News"),
                    ("sports", "Sports"),
                ],
                default="news",
                max_length=20,
            ),
        ),
    ]
