# Generated by Django 5.1.2 on 2024-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MI', 'Mindfulness and Meditation'), ('MH', 'Mental Health'), ('PW', 'Physical Wellness'), ('SR', 'Self-Care Rituals'), ('PG', 'Personal Growth')], default='SR', max_length=2),
        ),
    ]
