# Generated by Django 5.1.2 on 2024-11-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Mindfulness and Meditation', 'Mindfulness'), ('Mental Health', 'Mental Health'), ('Physical Wellness', 'Physical Wellness'), ('Self-Care Rituals', 'Self Care Rituals'), ('Personal Growth', 'Personal Growth')], default='Self-Care Rituals', max_length=50),
        ),
    ]
