# Generated by Django 5.1.2 on 2024-11-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MIN', 'Mindfulness and Meditation'), ('MHE', 'Mental Health'), ('PHW', 'Physical Wellness'), ('SCR', 'Self-Care Rituals'), ('PGR', 'Personal Growth')], default='SCR', max_length=50),
        ),
    ]
