# Generated by Django 5.1.2 on 2024-11-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='poster',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
