# Generated by Django 5.1.2 on 2024-11-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='poster',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
