# Generated by Django 5.1.2 on 2024-11-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_poster_alter_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Philosophy', 'Philosophy'), ('Medicine', 'Medicine'), ('Science', 'Scientists'), ('Fictional', 'Fictional Characters')], default='Philosophy', max_length=20),
        ),
    ]
