# Generated by Django 5.1.2 on 2024-11-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('other', 'other'), ('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('H&F', 'Health & Fitness'), ('E&CEducation & Career', 'Eductation')], default='other', max_length=1048),
        ),
    ]
