# Generated by Django 5.1.2 on 2024-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('NAT', 'Nature'), ('PHY', 'Physics'), ('CHE', 'Chemistry'), ('PLA', 'Plants'), ('MTH', 'Mathematics'), ('SCI', 'Science')], max_length=4),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/default.JPG', upload_to='images/'),
        ),
    ]
