# Generated by Django 5.1.2 on 2024-11-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_category_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='media/images/default.JPG', upload_to='images/'),
        ),
    ]
