# Generated by Django 5.1.2 on 2024-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('other', 'other'), ('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('H&F', 'Health & Fitness'), ('E&C', 'Education & Career')], default='other', max_length=56),
        ),
    ]
