# Generated by Django 5.1.2 on 2024-11-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Tech', 'Technology'), ('Life', 'Lifestyle'), ('Travel', 'Travel'), ('Food', 'Food'), ('Edu', 'Education')], default='Tech', max_length=10),
        ),
    ]
