# Generated by Django 5.1.2 on 2024-11-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0002_post_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_by',
            field=models.CharField(default='Anonymous', max_length=1024),
        ),
    ]
