# Generated by Django 5.1.2 on 2024-11-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0003_post_published_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('portrait', 'portrait'), ('nature', 'nature'), ('architecture', 'architecture'), ('animals', 'animals'), ('plants', 'plants'), ('objects', 'objects'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
