# Generated by Django 5.1.2 on 2024-11-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/blog.jpg.avif', null=True, upload_to='images/'),
        ),
    ]
