# Generated by Django 5.1.2 on 2024-11-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/images/blog.jpg.avif', upload_to='images/'),
        ),
    ]
