# Generated by Django 5.1.2 on 2024-11-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Technology'), ('Life', 'Lifestyle'), ('Edu', 'Education'), ('Hlth', 'Health'), ('Biz', 'Business'), ('Ent', 'Entertainment')], default='Tech', max_length=4),
        ),
    ]
