# Generated by Django 5.1.2 on 2024-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Technology'), ('Life', 'Lifestyle'), ('Edu', 'Education'), ('Hlth', 'Health'), ('Biz', 'Business'), ('Ent', 'Entertainment')], default='Tech', max_length=64),
        ),
    ]
